# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 灰蓝时光
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  个人原创与心得分享。大到编程、架构、技术管理、培训技能，小到瞬时感悟与点滴心得。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hltj.me"
# twitter_username: jekyllrb
github_username:  hltj

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
minima:
  date_format: "%Y-%m-%d"
excerpt_separator: "<!--more-->"
lang: "zh-Hans"
paginate: 20
paginate_path: "/page/:num"
